version: "2"
services:
  service:
    image: spider:1.1
    build: .
    container_name: proxy_spider
    volumes:
      - .:/code
    ports:
      - "50000:5000"
    environment:
      - ENV=development
    links:
      - mongodb
    entrypoint: /bin/bash -c "cd /code/web && python app.py"
    networks:
      - default

  mongodb:
    image: mongo:latest
    container_name: proxy_mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - default

networks:
  default:
    name: ip_proxy_network
